# Using the food dataset and user ratings, build a recommendation engine to recommend food for an individual Using a content-based or collaborative filtering approach.

------------------------------------------------------------------------------------------------------------------------------------------------------------

# BUILDING A FOOD RECOMMENDER ENGINE

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


I would be building a food recommendation engine using surprise library, I would also be breaking it into steps for easy understanding.
MRS Triple A this is EBUka writing, this is not an AI.
Read and be blessed.

## STEP 1: Importing Libraries and Dependencies

In [76]:
import pandas as pd
import numpy as np
from surprise import Reader, Dataset, KNNBasic, SVD, KNNWithZScore
from surprise.model_selection import train_test_split
from surprise import accuracy

## step 2: Reading our Data

In [ ]:
food =pd.read_csv(r"C:\Users\chukw\Documents\RAIN\AIML 2ND SEMESTER (File responses)\AIML 211 Exam\food_dataset\food_dataset\Food_data.csv")
ratings = pd.read_csv(r"C:\Users\chukw\Documents\RAIN\AIML 2ND SEMESTER (File responses)\AIML 211 Exam\food_dataset\food_dataset\ratings.csv")

In [78]:
food.head(10)

,Food_ID,Name,C_Type,Veg_Non,Describe
0,1,summer squash salad,Healthy Food,veg,"white balsamic vinegar, lemon juice, lemon rin..."
1,2,chicken minced salad,Healthy Food,non-veg,"olive oil, chicken mince, garlic (minced), oni..."
2,3,sweet chilli almonds,Snack,veg,"almonds whole, egg white, curry leaves, salt, ..."
3,4,tricolour salad,Healthy Food,veg,"vinegar, honey/sugar, soy sauce, salt, garlic ..."
4,5,christmas cake,Dessert,veg,"christmas dry fruits (pre-soaked), orange zest..."
5,6,japanese curry arancini with barley salsa,Japanese,veg,"japanese curry, sticky rice, cheese inside ric..."
6,7,chocolate nero cookies,Dessert,veg,"almonds, eggs, granulated sugar, bittersweet c..."
7,8,lamb and chargrilled bell pepper soup,Healthy Food,non-veg,"lamb bones (preferably shank and shoulder), on..."
8,9,cream of almond soup,Healthy Food,veg,"vegetable stock, skimmed milk, toasted almonds..."
9,10,broccoli and almond soup,Healthy Food,veg,"vegetable stock, broccoli, ground almonds (toa..."

In [79]:
ratings.head(10)

   User_ID  Food_ID  Rating
0      1.0     88.0     4.0
1      1.0     46.0     3.0
2      1.0     24.0     5.0
3      1.0     25.0     4.0
4      2.0     49.0     1.0
5      2.0     33.0     8.0
6      2.0    106.0     9.0
7      2.0     71.0     8.0
8      3.0     73.0     9.0
9      3.0    110.0    10.0

## Step 3: Preparing our Data for Suprise

In [80]:
#Surprise needs a format of (userid,itemid,rating)
df = ratings[['User_ID', 'Food_ID', 'Rating']]

In [81]:
df

     User_ID  Food_ID  Rating
0        1.0     88.0     4.0
1        1.0     46.0     3.0
2        1.0     24.0     5.0
3        1.0     25.0     4.0
4        2.0     49.0     1.0
..       ...      ...     ...
507     99.0     22.0     1.0
508    100.0     24.0    10.0
509    100.0    233.0    10.0
510    100.0     29.0     7.0
511      NaN      NaN     NaN

[512 rows x 3 columns]

#### Use reader assign the rating scale

In [82]:
# GETTING THE UNIQUE RANGE
df["Rating"].unique()

array([ 4.,  3.,  5.,  1.,  8.,  9., 10.,  6.,  2.,  7., nan])

##### since surprise is designed to work with sparse matrices, we can leave the NaN variables

In [83]:
reader = Reader(rating_scale=(1, 10))

#### Load data into Surprise's Dataset format

In [84]:
dataset = Dataset.load_from_df(df, reader)

## Step 4: Split Data into Train and Test Data

In [85]:
trainset, testset = train_test_split(dataset, test_size=0.25, random_state=100)

In [86]:
trainset

In [87]:
testset

[(52.0, 211.0, 1.0),
 (3.0, 110.0, 10.0),
 (49.0, 1.0, 5.0),
 (57.0, 164.0, 6.0),
 (38.0, 160.0, 2.0),
 (58.0, 137.0, 1.0),
 (78.0, 246.0, 9.0),
 (92.0, 6.0, 1.0),
 (48.0, 172.0, 8.0),
 (49.0, 139.0, 10.0),
 (19.0, 9.0, 9.0),
 (59.0, 145.0, 3.0),
 (54.0, 100.0, 1.0),
 (15.0, 29.0, 7.0),
 (22.0, 275.0, 4.0),
 (46.0, 59.0, 3.0),
 (21.0, 280.0, 5.0),
 (17.0, 7.0, 4.0),
 (63.0, 269.0, 3.0),
 (32.0, 290.0, 7.0),
 (98.0, 82.0, 2.0),
 (17.0, 278.0, 8.0),
 (42.0, 84.0, 2.0),
 (7.0, 31.0, 10.0),
 (62.0, 74.0, 7.0),
 (49.0, 6.0, 6.0),
 (7.0, 220.0, 3.0),
 (55.0, 288.0, 3.0),
 (35.0, 15.0, 1.0),
 (34.0, 12.0, 2.0),
 (68.0, 219.0, 9.0),
 (81.0, 197.0, 5.0),
 (42.0, 196.0, 9.0),
 (99.0, 93.0, 7.0),
 (39.0, 50.0, 7.0),
 (41.0, 51.0, 3.0),
 (81.0, 65.0, 3.0),
 (14.0, 17.0, 3.0),
 (26.0, 104.0, 6.0),
 (69.0, 46.0, 9.0),
 (36.0, 49.0, 2.0),
 (84.0, 253.0, 8.0),
 (1.0, 88.0, 4.0),
 (62.0, 215.0, 10.0),
 (91.0, 247.0, 5.0),
 (66.0, 192.0, 7.0),
 (13.0, 74.0, 8.0),
 (98.0, 194.0, 2.0),
 (4.0, 14.0, 5.0),
 (6.0, 185.0, 7.0),
 (19.0, 84.0, 10.0),
 (3.0, 46.0, 2.0),
 (14.0, 87.0, 8.0),
 (52.0, 187.0, 8.0),
 (39.0, 30.0, 6.0),
 (85.0, 202.0, 3.0),
 (80.0, 49.0, 9.0),
 (86.0, 159.0, 2.0),
 (37.0, 191.0, 1.0),
 (52.0, 69.0, 6.0),
 (33.0, 166.0, 4.0),
 (55.0, 90.0, 2.0),
 (69.0, 25.0, 10.0),
 (32.0, 244.0, 8.0),
 (57.0, 33.0, 3.0),
 (99.0, 152.0, 2.0),
 (80.0, 49.0, 8.0),
 (70.0, 83.0, 9.0),
 (46.0, 136.0, 10.0),
 (59.0, 43.0, 3.0),
 (54.0, 65.0, 7.0),
 (36.0, 25.0, 8.0),
 (11.0, 200.0, 10.0),
 (78.0, 32.0, 10.0),
 (19.0, 249.0, 10.0),
 (71.0, 137.0, 1.0),
 (1.0, 24.0, 5.0),
 (63.0, 61.0, 10.0),
 (48.0, 85.0, 3.0),
 (89.0, 163.0, 5.0),
 (36.0, 96.0, 7.0),
 (51.0, 151.0, 10.0),
 (59.0, 270.0, 5.0),
 (37.0, 218.0, 7.0),
 (82.0, 87.0, 7.0),
 (9.0, 91.0, 5.0),
 (27.0, 213.0, 3.0),
 (100.0, 233.0, 10.0),
 (86.0, 31.0, 6.0),
 (17.0, 114.0, 1.0),
 (2.0, 49.0, 1.0),
 (18.0, 31.0, 7.0),
 (41.0, 100.0, 3.0),
 (47.0, 199.0, 2.0),
 (28.0, 54.0, 7.0),
 (73.0, 135.0, 7.0),
 (80.0, 56.0, 7.0),
 (74.0, 56.0, 3.0),
 (69.0, 23.0, 10.0),
 (31.0, 74.0, 5.0),
 (73.0, 234.0, 2.0),
 (16.0, 270.0, 3.0),
 (17.0, 251.0, 5.0),
 (27.0, 207.0, 4.0),
 (77.0, 204.0, 9.0),
 (10.0, 100.0, 4.0),
 (59.0, 239.0, 10.0),
 (69.0, 126.0, 4.0),
 (44.0, 295.0, 10.0),
 (28.0, 50.0, 10.0),
 (100.0, 29.0, 7.0),
 (46.0, 68.0, 4.0),
 (54.0, 259.0, 9.0),
 (3.0, 65.0, 3.0),
 (43.0, 11.0, 4.0),
 (12.0, 38.0, 4.0),
 (9.0, 184.0, 6.0),
 (68.0, 22.0, 10.0),
 (85.0, 47.0, 9.0),
 (67.0, 203.0, 10.0),
 (76.0, 23.0, 1.0),
 (83.0, 41.0, 5.0),
 (15.0, 149.0, 1.0),
 (64.0, 303.0, 6.0),
 (68.0, 186.0, 10.0),
 (61.0, 22.0, 3.0),
 (53.0, 190.0, 10.0),
 (3.0, 73.0, 9.0)]

## Step 5: Train Model using KNNBasic(User-Based)

In [88]:
# Build KNNBasic model with Pearson Correlation between users
model = KNNBasic(k=40,min_k=3,
                sim_options={"name":"pearson",
                            "user_based":True,
                            "min_support": 10})

In [89]:
model.fit(trainset)

Computing the pearson similarity matrix...
Done computing similarity matrix.

#### Checking the prediction on a random set

In [90]:
model.predict(2,8)

Prediction(uid=2, iid=8, r_ui=None, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'})

In [91]:
model.predict(2,8).est

10

## Step 6: Testing on the Entire Dataset

In [92]:
predictions=model.test(testset)
predictions

[Prediction(uid=52.0, iid=211.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=3.0, iid=110.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=49.0, iid=1.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=57.0, iid=164.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=38.0, iid=160.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=58.0, iid=137.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=78.0, iid=246.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=92.0, iid=6.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=48.0, iid=172.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=49.0, iid=139.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=19.0, iid=9.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=59.0, iid=145.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=54.0, iid=100.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=15.0, iid=29.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=22.0, iid=275.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=46.0, iid=59.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=21.0, iid=280.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=17.0, iid=7.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=63.0, iid=269.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=32.0, iid=290.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=98.0, iid=82.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=17.0, iid=278.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=42.0, iid=84.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=7.0, iid=31.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=62.0, iid=74.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=49.0, iid=6.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=7.0, iid=220.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=55.0, iid=288.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=35.0, iid=15.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=34.0, iid=12.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=68.0, iid=219.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=81.0, iid=197.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=42.0, iid=196.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=99.0, iid=93.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=39.0, iid=50.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=41.0, iid=51.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=81.0, iid=65.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=14.0, iid=17.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=26.0, iid=104.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=69.0, iid=46.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=36.0, iid=49.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=84.0, iid=253.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=1.0, iid=88.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=62.0, iid=215.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=91.0, iid=247.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=66.0, iid=192.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=13.0, iid=74.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=98.0, iid=194.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=4.0, iid=14.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=6.0, iid=185.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=19.0, iid=84.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=3.0, iid=46.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=14.0, iid=87.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=52.0, iid=187.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=39.0, iid=30.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=85.0, iid=202.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=80.0, iid=49.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=86.0, iid=159.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=37.0, iid=191.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=52.0, iid=69.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=33.0, iid=166.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=55.0, iid=90.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=69.0, iid=25.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=32.0, iid=244.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=57.0, iid=33.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=99.0, iid=152.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=80.0, iid=49.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=70.0, iid=83.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=46.0, iid=136.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=59.0, iid=43.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=54.0, iid=65.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=36.0, iid=25.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=11.0, iid=200.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=78.0, iid=32.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=19.0, iid=249.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=71.0, iid=137.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=1.0, iid=24.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=63.0, iid=61.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=48.0, iid=85.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=89.0, iid=163.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=36.0, iid=96.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=51.0, iid=151.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=59.0, iid=270.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=37.0, iid=218.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=82.0, iid=87.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=9.0, iid=91.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=27.0, iid=213.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=100.0, iid=233.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=86.0, iid=31.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=17.0, iid=114.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=2.0, iid=49.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=18.0, iid=31.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=41.0, iid=100.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=47.0, iid=199.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=28.0, iid=54.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=73.0, iid=135.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=80.0, iid=56.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=74.0, iid=56.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=69.0, iid=23.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=31.0, iid=74.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=73.0, iid=234.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=16.0, iid=270.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=17.0, iid=251.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=27.0, iid=207.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=77.0, iid=204.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=10.0, iid=100.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=59.0, iid=239.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=69.0, iid=126.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=44.0, iid=295.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=28.0, iid=50.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=100.0, iid=29.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=46.0, iid=68.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=54.0, iid=259.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=3.0, iid=65.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=43.0, iid=11.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=12.0, iid=38.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=9.0, iid=184.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=68.0, iid=22.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=85.0, iid=47.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=67.0, iid=203.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=76.0, iid=23.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=83.0, iid=41.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=15.0, iid=149.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=64.0, iid=303.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=68.0, iid=186.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=61.0, iid=22.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=53.0, iid=190.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=3.0, iid=73.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'})]

## Step 7: Accuracy score with RMSE(Root-Mean-Square-Error)

In [93]:
print('KNNBasic Model Performance:')
KNNrmse = accuracy.rmse(predictions)

KNNBasic Model Performance:
RMSE: 5.2440

# Step 8: Trying with different Models

## Trying with SVD

In [94]:
svd_model = SVD(n_factors=50, n_epochs=20, random_state=42)


svd_model.fit(trainset)

In [95]:
svd_predictions = svd_model.test(testset)

In [96]:
print('SVD Model Performance:')
svd_rmse = accuracy.rmse(svd_predictions)

SVD Model Performance:
RMSE: 5.2440

## Trying with KNNWithZScore

In [97]:
model3= KNNWithZScore(k=40,min_k=3,
                sim_options={"name":"pearson",
                            "user_based":True,
                            "min_support": 10})

In [98]:
model3.fit(trainset)

Computing the pearson similarity matrix...
Done computing similarity matrix.

In [99]:
predictionsKNNZ=model3.test(testset)
predictionsKNNZ

[Prediction(uid=52.0, iid=211.0, r_ui=1.0, est=5.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=3.0, iid=110.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=49.0, iid=1.0, r_ui=5.0, est=6.166666666666667, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=57.0, iid=164.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=38.0, iid=160.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=58.0, iid=137.0, r_ui=1.0, est=10, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=78.0, iid=246.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=92.0, iid=6.0, r_ui=1.0, est=5.75, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=48.0, iid=172.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=49.0, iid=139.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=19.0, iid=9.0, r_ui=9.0, est=2.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=59.0, iid=145.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=54.0, iid=100.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=15.0, iid=29.0, r_ui=7.0, est=6.0, details={'actual_k': 1, 'was_impossible': False}),
 Prediction(uid=22.0, iid=275.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=46.0, iid=59.0, r_ui=3.0, est=5.666666666666667, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=21.0, iid=280.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=17.0, iid=7.0, r_ui=4.0, est=5.333333333333333, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=63.0, iid=269.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=32.0, iid=290.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=98.0, iid=82.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=17.0, iid=278.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=42.0, iid=84.0, r_ui=2.0, est=6.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=7.0, iid=31.0, r_ui=10.0, est=8.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=62.0, iid=74.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=49.0, iid=6.0, r_ui=6.0, est=6.166666666666667, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=7.0, iid=220.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=55.0, iid=288.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=35.0, iid=15.0, r_ui=1.0, est=3.6666666666666665, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=34.0, iid=12.0, r_ui=2.0, est=5.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=68.0, iid=219.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=81.0, iid=197.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=42.0, iid=196.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=99.0, iid=93.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=39.0, iid=50.0, r_ui=7.0, est=5.714285714285714, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=41.0, iid=51.0, r_ui=3.0, est=4.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=81.0, iid=65.0, r_ui=3.0, est=4.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=14.0, iid=17.0, r_ui=3.0, est=5.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=26.0, iid=104.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=69.0, iid=46.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=36.0, iid=49.0, r_ui=2.0, est=6.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=84.0, iid=253.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=1.0, iid=88.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=62.0, iid=215.0, r_ui=10.0, est=4.888888888888889, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=91.0, iid=247.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=66.0, iid=192.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=13.0, iid=74.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=98.0, iid=194.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=4.0, iid=14.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=6.0, iid=185.0, r_ui=7.0, est=4.333333333333333, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=19.0, iid=84.0, r_ui=10.0, est=2.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=3.0, iid=46.0, r_ui=2.0, est=4.8, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=14.0, iid=87.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=52.0, iid=187.0, r_ui=8.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=39.0, iid=30.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=85.0, iid=202.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=80.0, iid=49.0, r_ui=9.0, est=6.833333333333333, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=86.0, iid=159.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=37.0, iid=191.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=52.0, iid=69.0, r_ui=6.0, est=5.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=33.0, iid=166.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=55.0, iid=90.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=69.0, iid=25.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=32.0, iid=244.0, r_ui=8.0, est=4.444444444444445, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=57.0, iid=33.0, r_ui=3.0, est=4.25, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=99.0, iid=152.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=80.0, iid=49.0, r_ui=8.0, est=6.833333333333333, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=70.0, iid=83.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=46.0, iid=136.0, r_ui=10.0, est=5.666666666666667, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=59.0, iid=43.0, r_ui=3.0, est=8.666666666666666, details={'actual_k': 1, 'was_impossible': False}),
 Prediction(uid=54.0, iid=65.0, r_ui=7.0, est=3.857142857142857, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=36.0, iid=25.0, r_ui=8.0, est=6.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=11.0, iid=200.0, r_ui=10.0, est=4.8, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=78.0, iid=32.0, r_ui=10.0, est=4.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=19.0, iid=249.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=71.0, iid=137.0, r_ui=1.0, est=5.166666666666667, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=1.0, iid=24.0, r_ui=5.0, est=3.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=63.0, iid=61.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=48.0, iid=85.0, r_ui=3.0, est=4.25, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=89.0, iid=163.0, r_ui=5.0, est=6.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=36.0, iid=96.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=51.0, iid=151.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=59.0, iid=270.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=37.0, iid=218.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=82.0, iid=87.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=9.0, iid=91.0, r_ui=5.0, est=3.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=27.0, iid=213.0, r_ui=3.0, est=5.2, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=100.0, iid=233.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=86.0, iid=31.0, r_ui=6.0, est=4.25, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=17.0, iid=114.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=2.0, iid=49.0, r_ui=1.0, est=8.333333333333334, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=18.0, iid=31.0, r_ui=7.0, est=5.6, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=41.0, iid=100.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=47.0, iid=199.0, r_ui=2.0, est=5.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=28.0, iid=54.0, r_ui=7.0, est=9.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=73.0, iid=135.0, r_ui=7.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=80.0, iid=56.0, r_ui=7.0, est=6.833333333333333, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=74.0, iid=56.0, r_ui=3.0, est=6.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=69.0, iid=23.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=31.0, iid=74.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=73.0, iid=234.0, r_ui=2.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=16.0, iid=270.0, r_ui=3.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=17.0, iid=251.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=27.0, iid=207.0, r_ui=4.0, est=5.2, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=77.0, iid=204.0, r_ui=9.0, est=4.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=10.0, iid=100.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=59.0, iid=239.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=69.0, iid=126.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=44.0, iid=295.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=28.0, iid=50.0, r_ui=10.0, est=9.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=100.0, iid=29.0, r_ui=7.0, est=10, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=46.0, iid=68.0, r_ui=4.0, est=5.666666666666667, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=54.0, iid=259.0, r_ui=9.0, est=3.857142857142857, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=3.0, iid=65.0, r_ui=3.0, est=4.8, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=43.0, iid=11.0, r_ui=4.0, est=7.571428571428571, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=12.0, iid=38.0, r_ui=4.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=9.0, iid=184.0, r_ui=6.0, est=3.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=68.0, iid=22.0, r_ui=10.0, est=5.6, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=85.0, iid=47.0, r_ui=9.0, est=7.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=67.0, iid=203.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=76.0, iid=23.0, r_ui=1.0, est=5.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=83.0, iid=41.0, r_ui=5.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=15.0, iid=149.0, r_ui=1.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=64.0, iid=303.0, r_ui=6.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=68.0, iid=186.0, r_ui=10.0, est=5.6, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=61.0, iid=22.0, r_ui=3.0, est=4.5, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=53.0, iid=190.0, r_ui=10.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=3.0, iid=73.0, r_ui=9.0, est=10, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'})]

### A lot of the values contain details={'was_impossible': True, 'reason': 'User and/or item is unknown.'} issue

In [100]:
print('KNNWithZScore Model Performance:')
KNNZ = accuracy.rmse(predictionsKNNZ)

KNNWithZScore Model Performance:
RMSE: 4.3638

# Based on the models built, KNNWithZScore has the lowest RMSE.
# The RMSE values are a bit too high,I shall try to improve model performance.

In [101]:
from surprise.model_selection import cross_validate

In [102]:
results = cross_validate(model3, dataset, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Computing the pearson similarity matrix...
Done computing similarity matrix.
Computing the pearson similarity matrix...
Done computing similarity matrix.
Computing the pearson similarity matrix...
Done computing similarity matrix.
Computing the pearson similarity matrix...
Done computing similarity matrix.
Computing the pearson similarity matrix...
Done computing similarity matrix.
Evaluating RMSE, MAE of algorithm KNNWithZScore on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    4.1373  4.1812  nan     4.5912  4.3080  nan     nan
MAE (testset)     3.3027  3.3466  nan     3.8191  3.5062  nan     nan
Fit time          0.00    0.00    0.00    0.00    0.00    0.00    0.00
Test time         0.00    0.00    0.00    0.00    0.00    0.00    0.00

# Experiencing Possible Cold Start Issues

# Trying to clean the dataset

In [ ]:
df = df.groupby('Food_ID').filter(lambda x: len(x) > 5)

In [106]:
df.head(10)

     User_ID  Food_ID  Rating
4        2.0     49.0     1.0
46       8.0    163.0     5.0
89      17.0     23.0     4.0
122     24.0     23.0     2.0
144     28.0      5.0    10.0
174     34.0    163.0     6.0
185     36.0     49.0     2.0
188     36.0     23.0     1.0
208     39.0      5.0    10.0
246     47.0     49.0    10.0

In [108]:

df["Rating"].unique()

array([ 1.,  5.,  4.,  2., 10.,  6.,  7.,  8.,  9.,  3.])

In [109]:
reader = Reader(rating_scale=(1,10))

In [110]:
dataset= Dataset.load_from_df(df,reader)

In [111]:
trainset,testset = train_test_split(dataset,test_size=0.25,random_state=101)

In [113]:
model = KNNWithZScore(k=40,min_k=3,
                sim_options={"name":"pearson",
                            "user_based":True,
                            "min_support": 10})

In [114]:
model.fit(trainset)

Computing the pearson similarity matrix...
Done computing similarity matrix.

In [115]:
predictions=model.test(testset)
predictions

[Prediction(uid=73.0, iid=5.0, r_ui=7.0, est=4.611111111111111, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=47.0, iid=49.0, r_ui=10.0, est=4.611111111111111, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=77.0, iid=163.0, r_ui=2.0, est=4.611111111111111, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=99.0, iid=49.0, r_ui=3.0, est=4.611111111111111, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid=36.0, iid=49.0, r_ui=2.0, est=1, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid=80.0, iid=49.0, r_ui=8.0, est=9.0, details={'actual_k': 1, 'was_impossible': False}),
 Prediction(uid=64.0, iid=23.0, r_ui=2.0, est=4.611111111111111, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'})]

In [117]:
print("The RMSE accuracy after cleaning the data:")
acc2 =accuracy.rmse(predictions)

The RMSE accuracy after cleaning the data:
RMSE: 2.7511

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


# After Cleaning the data in conjuction with KNNwithZScore a better model has been engineered.
# With an RMSE = 2.

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------